version: '3.8'

services:
  finos-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finos_app
    restart: always
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PYTHON_BACKEND_URL=http://127.0.0.1:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
